<!doctype html><html><head><meta charset="utf-8"><style>
@page{margin:28px}body{font-family:"DejaVu Sans",sans-serif;color:#17211e;font-size:10px}.hero{background:#0e6b57;color:white;padding:18px 20px}h1{margin:0;font-size:23px}.sub{color:#d9f3ec}.identity,.summary{margin-top:12px;padding:10px;border:1px solid #cbd8d3}.identity{background:#eef8f5;border-left:4px solid #0e6b57}table{border-collapse:collapse;width:100%;margin-top:12px}th{background:#0e6b57;color:white;text-align:left;padding:7px}td{padding:7px;border-bottom:1px solid #dfe7e4}.n{text-align:right}.footer{margin-top:20px;color:#66746f;font-size:8px}.total{font-weight:bold;background:#eef8f5}
</style></head><body>
<div class="hero"><h1>DairyCare</h1><div class="sub">{{ $title }}</div></div>
<div class="identity"><strong>Farm:</strong> {{ $farm->name }} &nbsp; | &nbsp; <strong>Owner:</strong> {{ $owner?->name ?? 'Not provided' }} &nbsp; | &nbsp; <strong>Phone:</strong> {{ $owner?->phone_number ?? 'Not provided' }}</div>
@if($manifest)
<div class="summary"><strong>Delivery:</strong> {{ $manifest->delivery_number }} &nbsp; <strong>Date:</strong> {{ $manifest->delivery_date->format('Y-m-d') }} &nbsp; <strong>Route:</strong> {{ $manifest->route->name }}<br><strong>Driver:</strong> {{ $manifest->driver->name }} &nbsp; <strong>Vehicle:</strong> {{ $manifest->vehicle->registration_number }} &nbsp; <strong>Status:</strong> {{ ucfirst(str_replace('_',' ',$manifest->status)) }}</div>
<table><thead><tr><th>#</th><th>Customer</th><th>Invoice</th><th class="n">Planned L</th><th class="n">Delivered L</th><th class="n">Returned L</th><th class="n">Rejected L</th><th>Acknowledged by</th></tr></thead><tbody>
@foreach($manifest->stops as $stop)<tr><td>{{ $stop->stop_order }}</td><td>{{ $stop->customer->name }}</td><td>{{ $stop->sale->invoice_number }}</td><td class="n">{{ number_format((float)$stop->planned_quantity,3) }}</td><td class="n">{{ number_format((float)$stop->delivered_quantity,3) }}</td><td class="n">{{ number_format((float)$stop->returned_quantity,3) }}</td><td class="n">{{ number_format((float)$stop->rejected_quantity,3) }}</td><td>{{ $stop->acknowledged_by ?? '-' }}</td></tr>@endforeach
<tr class="total"><td colspan="3">Totals</td><td class="n">{{ number_format((float)$manifest->planned_quantity,3) }}</td><td class="n">{{ number_format((float)$manifest->delivered_quantity,3) }}</td><td class="n">{{ number_format((float)$manifest->returned_quantity,3) }}</td><td class="n">{{ number_format((float)$manifest->rejected_quantity,3) }}</td><td></td></tr></tbody></table>
@else
<div class="summary"><strong>Refund:</strong> {{ $refund->refund_number }} &nbsp; <strong>Date:</strong> {{ $refund->refund_date->format('Y-m-d') }}<br><strong>Customer:</strong> {{ $refund->customer->name }} &nbsp; <strong>Milk invoice:</strong> {{ $refund->sale->invoice_number }} &nbsp; <strong>Return:</strong> {{ $refund->saleReturn->return_number }}</div>
<table><tr><th>Description</th><th>Payment method</th><th>Reference</th><th class="n">Amount</th></tr><tr><td>Customer milk-return refund</td><td>{{ ucfirst(str_replace('_',' ',$refund->payment_method)) }}</td><td>{{ $refund->reference ?? '-' }}</td><td class="n"><strong>PKR {{ number_format((float)$refund->amount,2) }}</strong></td></tr></table>
@endif
<div class="footer">Generated {{ now()->setTimezone($farm->timezone)->format('Y-m-d H:i:s T') }} from DairyCare. This document reflects saved, auditable records.</div>
</body></html>
