<?php

use App\Http\Controllers\Api\V1\AlertController;
use App\Http\Controllers\Api\V1\AnimalBreedController;
use App\Http\Controllers\Api\V1\AnimalController;
use App\Http\Controllers\Api\V1\AnimalFeedConsumptionController;
use App\Http\Controllers\Api\V1\AnimalGroupController;
use App\Http\Controllers\Api\V1\AnimalHealthController;
use App\Http\Controllers\Api\V1\AnimalMilkEntryController;
use App\Http\Controllers\Api\V1\AnimalMovementController;
use App\Http\Controllers\Api\V1\AnimalPhotoController;
use App\Http\Controllers\Api\V1\AnimalPurchaseController;
use App\Http\Controllers\Api\V1\AnimalSaleController;
use App\Http\Controllers\Api\V1\AnimalSpeciesController;
use App\Http\Controllers\Api\V1\AnimalStatusController;
use App\Http\Controllers\Api\V1\AnimalTreatmentController;
use App\Http\Controllers\Api\V1\AnimalWeightController;
use App\Http\Controllers\Api\V1\AuthController;
use App\Http\Controllers\Api\V1\BreedingController;
use App\Http\Controllers\Api\V1\CalfCareController;
use App\Http\Controllers\Api\V1\CustomerController;
use App\Http\Controllers\Api\V1\DailyFeedIssueController;
use App\Http\Controllers\Api\V1\DailyProductionReportController;
use App\Http\Controllers\Api\V1\DeliveryController;
use App\Http\Controllers\Api\V1\EmployeeController;
use App\Http\Controllers\Api\V1\EmployeeLoanController;
use App\Http\Controllers\Api\V1\FamilyAccountController;
use App\Http\Controllers\Api\V1\FarmController;
use App\Http\Controllers\Api\V1\FeedAnalysisController;
use App\Http\Controllers\Api\V1\FeedRationPlanController;
use App\Http\Controllers\Api\V1\FinanceController;
use App\Http\Controllers\Api\V1\FinancialAccountController;
use App\Http\Controllers\Api\V1\HealthKnowledgeController;
use App\Http\Controllers\Api\V1\InventoryController;
use App\Http\Controllers\Api\V1\InventoryOperationsController;
use App\Http\Controllers\Api\V1\MilkProductionController;
use App\Http\Controllers\Api\V1\MilkSaleController;
use App\Http\Controllers\Api\V1\OrganizationController;
use App\Http\Controllers\Api\V1\OwnerAccountController;
use App\Http\Controllers\Api\V1\PayrollController;
use App\Http\Controllers\Api\V1\PreventiveCareController;
use App\Http\Controllers\Api\V1\ProfileController;
use App\Http\Controllers\Api\V1\PurchaseOrderController;
use App\Http\Controllers\Api\V1\ShedController;
use App\Http\Controllers\Api\V1\SupplierController;
use App\Http\Controllers\Api\V1\SupplierInvoiceController;
use App\Http\Controllers\Api\V1\SyncController;
use App\Http\Controllers\Api\V1\VisitorController;
use Illuminate\Support\Facades\Route;

Route::prefix('v1')->group(function (): void {
    Route::post('auth/login', [AuthController::class, 'login'])->middleware('throttle:login');
    Route::post('auth/renew', [AuthController::class, 'renew'])->middleware('throttle:renew');
    Route::post('auth/owner-signup', [OwnerAccountController::class, 'signup'])->middleware('throttle:signup');
    Route::post('auth/family-invite/inspect', [OwnerAccountController::class, 'inspectFamilyInvite'])->middleware('throttle:signup');
    Route::post('auth/family-signup', [OwnerAccountController::class, 'familySignup'])->middleware('throttle:signup');

    Route::middleware('auth.opaque')->group(function (): void {
        Route::post('auth/logout', [AuthController::class, 'logout']);
        Route::get('auth/me', [AuthController::class, 'me']);
        Route::get('auth/sessions', [AuthController::class, 'sessions'])->middleware(['tenant', 'permission:sessions.view_own']);
        Route::delete('auth/sessions/{session}', [AuthController::class, 'revokeSession'])->middleware(['tenant', 'permission:sessions.revoke_own']);
        Route::post('auth/switch-organization', [AuthController::class, 'switchOrganization']);
        Route::post('auth/switch-farm', [AuthController::class, 'switchFarm']);
        Route::get('auth/profile', [ProfileController::class, 'show']);
        Route::patch('auth/profile', [ProfileController::class, 'update']);
        Route::post('auth/profile/photo', [ProfileController::class, 'uploadPhoto']);
        Route::delete('auth/profile/photo', [ProfileController::class, 'deletePhoto']);
        Route::get('auth/profile/photo', [ProfileController::class, 'photo']);
        Route::get('organizations', [OrganizationController::class, 'index']);

        Route::middleware('tenant')->group(function (): void {
            Route::get('profile-photos/{user}', [ProfileController::class, 'memberPhoto']);
            Route::get('family-members', [FamilyAccountController::class, 'index'])->middleware('permission:users.view');
            Route::delete('family-members/{membership}', [FamilyAccountController::class, 'remove'])->middleware('permission:users.manage');
            Route::post('family-members/{membership}/restore', [FamilyAccountController::class, 'restore'])->middleware('permission:users.manage');
            Route::get('family-invite', [FamilyAccountController::class, 'invite'])->middleware('permission:users.manage');
            Route::post('family-invite', [FamilyAccountController::class, 'rotateInvite'])->middleware('permission:users.manage');
            Route::delete('family-invite', [FamilyAccountController::class, 'disableInvite'])->middleware('permission:users.manage');
            Route::get('organizations/{organization}', [OrganizationController::class, 'show'])->middleware('permission:organizations.view');
            Route::patch('organizations/{organization}', [OrganizationController::class, 'update'])->middleware('permission:organizations.update');
            Route::get('farms', [FarmController::class, 'index'])->middleware('permission:farms.view');
            Route::post('farms', [FarmController::class, 'store'])->middleware('permission:farms.create');
            Route::get('farms/{farm}', [FarmController::class, 'show'])->middleware('permission:farms.view');
            Route::patch('farms/{farm}', [FarmController::class, 'update'])->middleware('permission:farms.update');
            Route::delete('farms/{farm}', [FarmController::class, 'destroy'])->middleware('permission:farms.archive');
            Route::get('farms/{farm}/sheds', [ShedController::class, 'index'])->middleware('permission:sheds.view');
            Route::post('farms/{farm}/sheds', [ShedController::class, 'store'])->middleware('permission:sheds.create');
            Route::get('sheds/{shed}', [ShedController::class, 'show'])->middleware('permission:sheds.view');
            Route::patch('sheds/{shed}', [ShedController::class, 'update'])->middleware('permission:sheds.update');
            Route::delete('sheds/{shed}', [ShedController::class, 'destroy'])->middleware('permission:sheds.archive');
            Route::get('animal-species', [AnimalSpeciesController::class, 'index'])->middleware('permission:animals.view');
            Route::get('animal-breeds', [AnimalBreedController::class, 'index'])->middleware('permission:animal_breeds.view');
            Route::post('animal-breeds', [AnimalBreedController::class, 'store'])->middleware('permission:animal_breeds.manage');
            Route::get('animal-breeds/{breed}', [AnimalBreedController::class, 'show'])->middleware('permission:animal_breeds.view');
            Route::patch('animal-breeds/{breed}', [AnimalBreedController::class, 'update'])->middleware('permission:animal_breeds.manage');
            Route::delete('animal-breeds/{breed}', [AnimalBreedController::class, 'destroy'])->middleware('permission:animal_breeds.manage');
            Route::get('animal-groups', [AnimalGroupController::class, 'index'])->middleware('permission:animal_groups.view');
            Route::post('animal-groups', [AnimalGroupController::class, 'store'])->middleware('permission:animal_groups.manage');
            Route::get('animal-groups/{group}', [AnimalGroupController::class, 'show'])->middleware('permission:animal_groups.view');
            Route::patch('animal-groups/{group}', [AnimalGroupController::class, 'update'])->middleware('permission:animal_groups.manage');
            Route::delete('animal-groups/{group}', [AnimalGroupController::class, 'destroy'])->middleware('permission:animal_groups.manage');
            Route::get('animals', [AnimalController::class, 'index'])->middleware('permission:animals.view');
            Route::post('animals', [AnimalController::class, 'store'])->middleware('permission:animals.create');
            Route::get('animals/{animal}/movements', [AnimalMovementController::class, 'index'])->middleware('permission:animal_movements.view');
            Route::post('animals/{animal}/movements', [AnimalMovementController::class, 'store'])->middleware('permission:animals.move');
            Route::get('animals/{animal}/weights', [AnimalWeightController::class, 'index'])->middleware('permission:animals.view_weight_history');
            Route::post('animals/{animal}/weights', [AnimalWeightController::class, 'store'])->middleware('permission:animals.record_weight');
            Route::get('animals/{animal}/status-history', [AnimalStatusController::class, 'index'])->middleware('permission:animals.view_status_history');
            Route::post('animals/{animal}/status-changes', [AnimalStatusController::class, 'store'])->middleware('permission:animals.change_status');
            Route::get('animals/{animal}/feed-consumptions', [AnimalFeedConsumptionController::class, 'index'])->middleware('permission:inventory.view');
            Route::post('animals/{animal}/feed-consumptions', [AnimalFeedConsumptionController::class, 'store'])->middleware('permission:inventory.manage');
            Route::get('animals/{animal}/milk-entries', [AnimalMilkEntryController::class, 'index'])->middleware('permission:milk.view');
            Route::get('health/symptoms', [AnimalHealthController::class, 'symptoms'])->middleware('permission:health.view');
            Route::get('health/knowledge', [HealthKnowledgeController::class, 'index'])->middleware('permission:health.view');
            Route::get('health/ai/dataset.json', [HealthKnowledgeController::class, 'export'])->middleware('permission:health.ai.export');
            Route::get('health/ai/evaluation-cases', [HealthKnowledgeController::class, 'evaluationCases'])->middleware('permission:health.ai.review');
            Route::get('health/ai/evaluation-cases/{case}/reviews', [HealthKnowledgeController::class, 'evaluationCaseReviews'])->middleware('permission:health.ai.review');
            Route::post('health/ai/evaluation-cases/{case}/review', [HealthKnowledgeController::class, 'reviewEvaluationCase'])->middleware('permission:health.ai.review');
            Route::post('health/ai/ask', [HealthKnowledgeController::class, 'ask'])->middleware(['permission:health.view', 'throttle:health-ai']);
            Route::get('health/medicine-evidence', [HealthKnowledgeController::class, 'medicineEvidence'])->middleware('permission:health.medicine_evidence.manage');
            Route::post('health/medicine-evidence', [HealthKnowledgeController::class, 'storeMedicineEvidence'])->middleware('permission:health.medicine_evidence.manage');
            Route::post('health/medicine-evidence/{evidence}/review', [HealthKnowledgeController::class, 'reviewMedicineEvidence'])->middleware('permission:health.medicine_evidence.review');
            Route::post('health/knowledge/{disease}/review', [HealthKnowledgeController::class, 'review'])->middleware('permission:health.knowledge.review');
            Route::get('health/preventive-care/due', [PreventiveCareController::class, 'due'])->middleware('permission:health.preventive.view');
            Route::get('animals/{animal}/preventive-care', [PreventiveCareController::class, 'index'])->middleware('permission:health.preventive.view');
            Route::post('health/preventive-care', [PreventiveCareController::class, 'store'])->middleware('permission:health.preventive.manage');
            Route::get('breeding/due', [BreedingController::class, 'due'])->middleware('permission:breeding.view');
            Route::get('animals/{animal}/breeding', [BreedingController::class, 'index'])->middleware('permission:breeding.view');
            Route::post('animals/{animal}/breeding/{event}', [BreedingController::class, 'store'])->middleware('permission:breeding.manage');
            Route::get('calves/due', [CalfCareController::class, 'due'])->middleware('permission:calves.view');
            Route::get('animals/{animal}/calf-care', [CalfCareController::class, 'show'])->middleware('permission:calves.view');
            Route::post('animals/{animal}/calf-care', [CalfCareController::class, 'store'])->middleware('permission:calves.manage');
            Route::get('alerts', [AlertController::class, 'index'])->middleware('permission:alerts.view');
            Route::patch('alerts/{alert}', [AlertController::class, 'update'])->middleware('permission:alerts.manage');
            Route::get('animals/{animal}/health-cases', [AnimalHealthController::class, 'index'])->middleware('permission:health.view');
            Route::post('animals/{animal}/health-assessments', [AnimalHealthController::class, 'store'])->middleware('permission:health.assess');
            Route::get('animals/{animal}/treatments', [AnimalTreatmentController::class, 'index'])->middleware('permission:health.view');
            Route::post('animals/{animal}/treatments', [AnimalTreatmentController::class, 'store'])->middleware('permission:health.treat');
            Route::post('animals/{animal}/photos', [AnimalPhotoController::class, 'store'])->middleware('permission:animals.update');
            Route::get('animal-photos/{photo}', [AnimalPhotoController::class, 'show'])->middleware('permission:animals.view');
            Route::get('animals/{animal}', [AnimalController::class, 'show'])->middleware('permission:animals.view');
            Route::patch('animals/{animal}', [AnimalController::class, 'update'])->middleware('permission:animals.update');
            Route::delete('animals/{animal}', [AnimalController::class, 'destroy'])->middleware('permission:animals.archive');
            Route::post('animals/{animal}/restore', [AnimalController::class, 'restore'])->middleware('permission:animals.restore');
            Route::get('animal-purchases', [AnimalPurchaseController::class, 'index'])->middleware('permission:animals.view');
            Route::post('animal-purchases', [AnimalPurchaseController::class, 'store'])->middleware('permission:animals.create');
            Route::get('animal-sales', [AnimalSaleController::class, 'index'])->middleware('permission:animals.view');

            Route::get('reports/daily-animal-production', [DailyProductionReportController::class, 'index'])->middleware('permission:milk.view');
            Route::post('animal-sales', [AnimalSaleController::class, 'store'])->middleware('permission:animals.update');
            Route::get('animal-movements/{movement}', [AnimalMovementController::class, 'show'])->middleware('permission:animal_movements.view');
            Route::post('animal-movements/{movement}/approve', [AnimalMovementController::class, 'approve'])->middleware('permission:animal_movements.approve');
            Route::post('animal-movements/{movement}/reject', [AnimalMovementController::class, 'reject'])->middleware('permission:animal_movements.reject');
            Route::post('animal-movements/{movement}/cancel', [AnimalMovementController::class, 'cancel'])->middleware('permission:animal_movements.cancel');
            Route::get('animal-weights/{weight}', [AnimalWeightController::class, 'show'])->middleware('permission:animals.view_weight_history');
            Route::post('animal-weights/{weight}/correct', [AnimalWeightController::class, 'correct'])->middleware('permission:animals.correct_weight');
            Route::get('inventory', [InventoryController::class, 'dashboard'])->middleware('permission:inventory.view');
            Route::get('inventory/usage', [InventoryController::class, 'usageHistory'])->middleware('permission:inventory.view');
            Route::get('inventory/{kind}', [InventoryController::class, 'index'])->middleware('permission:inventory.view');
            Route::get('inventory/{kind}/exports/receipt', [InventoryController::class, 'receiptExport'])->middleware('permission:inventory.export');
            Route::get('inventory/{kind}/exports/spreadsheet', [InventoryController::class, 'spreadsheetExport'])->middleware('permission:inventory.export');
            Route::post('inventory/{kind}/items', [InventoryController::class, 'store'])->middleware('permission:inventory.manage');
            Route::patch('inventory/{kind}/items/{item}', [InventoryController::class, 'update'])->middleware('permission:inventory.manage');
            Route::delete('inventory/{kind}/items/{item}', [InventoryController::class, 'archive'])->middleware('permission:inventory.manage');
            Route::post('inventory/{kind}/items/{item}/receipts', [InventoryController::class, 'receipt'])->middleware('permission:inventory.manage');
            Route::post('inventory/{kind}/items/{item}/usage', [InventoryController::class, 'usage'])->middleware('permission:inventory.manage');
            Route::get('inventory/{kind}/items/{item}/movements', [InventoryController::class, 'movements'])->middleware('permission:inventory.view');
            Route::post('inventory/items/{item}/adjustments', [InventoryOperationsController::class, 'adjustments'])->middleware('permission:inventory.adjust');
            Route::post('inventory/items/{item}/transfers', [InventoryOperationsController::class, 'transfers'])->middleware('permission:inventory.transfer');
            Route::get('milk/daily', [MilkProductionController::class, 'daily'])->middleware('permission:milk.view');
            Route::post('milk/entries/bulk', [MilkProductionController::class, 'storeBulk'])->middleware('permission:milk.create');
            Route::post('milk/entries/{entry}/correct', [MilkProductionController::class, 'correct'])->middleware('permission:milk.correct');
            Route::get('milk-sales', [MilkSaleController::class, 'index'])->middleware('permission:milk_sales.view');
            Route::post('milk-sales', [MilkSaleController::class, 'store'])->middleware('permission:milk_sales.manage');
            Route::post('milk-sales/{sale}/confirm', [MilkSaleController::class, 'confirm'])->middleware('permission:milk_sales.confirm');
            Route::post('milk-sales/{sale}/payments', [MilkSaleController::class, 'pay'])->middleware('permission:customer_payments.manage');
            Route::post('milk-sales/{sale}/cancel', [MilkSaleController::class, 'cancel'])->middleware('permission:milk_sales.cancel');
            Route::get('deliveries', [DeliveryController::class, 'overview'])->middleware('permission:deliveries.view');
            Route::post('delivery-routes', [DeliveryController::class, 'routeStore'])->middleware('permission:deliveries.manage');
            Route::post('delivery-vehicles', [DeliveryController::class, 'vehicleStore'])->middleware('permission:deliveries.manage');
            Route::post('delivery-drivers', [DeliveryController::class, 'driverStore'])->middleware('permission:deliveries.manage');
            Route::post('delivery-manifests', [DeliveryController::class, 'manifestStore'])->middleware('permission:deliveries.manage');
            Route::post('delivery-manifests/{manifest}/dispatch', [DeliveryController::class, 'dispatch'])->middleware('permission:deliveries.dispatch');
            Route::post('delivery-manifests/{manifest}/stops/{stop}/complete', [DeliveryController::class, 'completeStop'])->middleware('permission:deliveries.complete');
            Route::post('delivery-manifests/{manifest}/stops/{stop}/proof', [DeliveryController::class, 'uploadProof'])->middleware('permission:deliveries.complete');
            Route::get('delivery-manifests/{manifest}/stops/{stop}/proof', [DeliveryController::class, 'proof'])->middleware('permission:deliveries.view');
            Route::post('delivery-manifests/{manifest}/stops/{stop}/refunds', [DeliveryController::class, 'refund'])->middleware('permission:customer_refunds.manage');
            Route::get('delivery-manifests/{manifest}/delivery-note.pdf', [DeliveryController::class, 'deliveryNote'])->middleware('permission:deliveries.view');
            Route::get('customer-refunds/{refund}/receipt.pdf', [DeliveryController::class, 'refundReceipt'])->middleware('permission:deliveries.view');
            Route::get('deliveries/export.xlsx', [DeliveryController::class, 'export'])->middleware('permission:deliveries.view');
            Route::get('employees', [EmployeeController::class, 'index'])->middleware('permission:employees.view');
            Route::get('visitors', [VisitorController::class, 'index'])->middleware('permission:visitors.view');
            Route::post('visitors', [VisitorController::class, 'store'])->middleware('permission:visitors.manage');
            Route::delete('visitors/{visitor}', [VisitorController::class, 'destroy'])->middleware('permission:visitors.manage');
            Route::post('employees', [EmployeeController::class, 'store'])->middleware('permission:employees.manage');
            Route::patch('employees/{employee}', [EmployeeController::class, 'update'])->middleware('permission:employees.manage');
            Route::delete('employees/{employee}', [EmployeeController::class, 'archive'])->middleware('permission:employees.manage');
            Route::post('employees/{employee}/restore', [EmployeeController::class, 'restore'])->middleware('permission:employees.manage');
            Route::get('employee-loans', [EmployeeLoanController::class, 'index'])->middleware('permission:employee_loans.view');
            Route::post('employee-loans', [EmployeeLoanController::class, 'store'])->middleware('permission:employee_loans.manage');
            Route::get('payroll', [PayrollController::class, 'index'])->middleware('permission:payroll.view');
            Route::post('payroll/generate', [PayrollController::class, 'generate'])->middleware('permission:payroll.process');
            Route::post('payroll/{period}/approve', [PayrollController::class, 'approve'])->middleware('permission:payroll.process');
            Route::post('payroll/{period}/pay', [PayrollController::class, 'pay'])->middleware('permission:payroll.process');
            Route::get('finance/overview', [FinanceController::class, 'overview'])->middleware('permission:finance.view');
            Route::get('finance/income', [FinanceController::class, 'income'])->middleware('permission:finance.view');
            Route::post('finance/income', [FinanceController::class, 'storeIncome'])->middleware('permission:finance.manage');
            Route::get('finance/expenses', [FinanceController::class, 'expenses'])->middleware('permission:finance.view');
            Route::post('finance/expenses', [FinanceController::class, 'storeExpense'])->middleware('permission:finance.manage');
            Route::get('finance/ledger', [FinanceController::class, 'ledger'])->middleware('permission:finance.view');
            Route::get('finance/profit-loss', [FinanceController::class, 'profitLoss'])->middleware('permission:finance.view');
            Route::get('finance/accounts', [FinancialAccountController::class, 'index'])->middleware('permission:finance_accounts.view');
            Route::post('finance/accounts', [FinancialAccountController::class, 'store'])->middleware('permission:finance_accounts.manage');
            Route::post('finance/account-transfers', [FinancialAccountController::class, 'transfer'])->middleware('permission:finance_accounts.transfer');

            Route::get('suppliers', [SupplierController::class, 'index'])->middleware('permission:suppliers.view');
            Route::post('suppliers', [SupplierController::class, 'store'])->middleware('permission:suppliers.manage');
            Route::patch('suppliers/{supplier}', [SupplierController::class, 'update'])->middleware('permission:suppliers.manage');
            Route::delete('suppliers/{supplier}', [SupplierController::class, 'destroy'])->middleware('permission:suppliers.manage');
            Route::get('suppliers/{supplier}/ledger', [SupplierController::class, 'ledger'])->middleware('permission:commercial_ledgers.view');
            Route::get('customers', [CustomerController::class, 'index'])->middleware('permission:customers.view');
            Route::post('customers', [CustomerController::class, 'store'])->middleware('permission:customers.manage');
            Route::patch('customers/{customer}', [CustomerController::class, 'update'])->middleware('permission:customers.manage');
            Route::delete('customers/{customer}', [CustomerController::class, 'destroy'])->middleware('permission:customers.manage');
            Route::get('customers/{customer}/ledger', [CustomerController::class, 'ledger'])->middleware('permission:commercial_ledgers.view');
            Route::get('purchase-orders', [PurchaseOrderController::class, 'index'])->middleware('permission:purchases.view');
            Route::post('purchase-orders', [PurchaseOrderController::class, 'store'])->middleware('permission:purchases.manage');
            Route::post('purchase-orders/{order}/approve', [PurchaseOrderController::class, 'approve'])->middleware('permission:purchases.approve');
            Route::post('purchase-orders/{order}/receipts', [PurchaseOrderController::class, 'receive'])->middleware('permission:purchases.receive');
            Route::get('supplier-invoices', [SupplierInvoiceController::class, 'index'])->middleware('permission:supplier_invoices.view');
            Route::post('supplier-invoices', [SupplierInvoiceController::class, 'store'])->middleware('permission:supplier_invoices.manage');
            Route::post('supplier-invoices/{invoice}/payments', [SupplierInvoiceController::class, 'pay'])->middleware('permission:supplier_payments.manage');

            Route::get('feed-ration-plans', [FeedRationPlanController::class, 'index'])->middleware('permission:inventory.view');
            Route::post('feed-ration-plans', [FeedRationPlanController::class, 'store'])->middleware('permission:inventory.manage');
            Route::get('feed-ration-plans/{plan}', [FeedRationPlanController::class, 'show'])->middleware('permission:inventory.view');
            Route::get('daily-feed-issues', [DailyFeedIssueController::class, 'index'])->middleware('permission:inventory.view');
            Route::get('feed-analysis', [FeedAnalysisController::class, 'show'])->middleware('permission:inventory.view');
            Route::post('daily-feed-issues', [DailyFeedIssueController::class, 'store'])->middleware('permission:inventory.manage');

            Route::get('sync/bootstrap', [SyncController::class, 'bootstrap']);
            Route::get('sync/changes', [SyncController::class, 'changes']);
        });
    });
});
