<?php

use App\Http\Controllers\Api\V1\AnimalBreedController;
use App\Http\Controllers\Api\V1\AnimalController;
use App\Http\Controllers\Api\V1\AnimalGroupController;
use App\Http\Controllers\Api\V1\AnimalMovementController;
use App\Http\Controllers\Api\V1\AnimalSpeciesController;
use App\Http\Controllers\Api\V1\AnimalStatusController;
use App\Http\Controllers\Api\V1\AnimalWeightController;
use App\Http\Controllers\Api\V1\AuthController;
use App\Http\Controllers\Api\V1\FamilyAccountController;
use App\Http\Controllers\Api\V1\FarmController;
use App\Http\Controllers\Api\V1\InventoryController;
use App\Http\Controllers\Api\V1\MilkProductionController;
use App\Http\Controllers\Api\V1\OrganizationController;
use App\Http\Controllers\Api\V1\OwnerAccountController;
use App\Http\Controllers\Api\V1\ProfileController;
use App\Http\Controllers\Api\V1\ShedController;
use App\Http\Controllers\Api\V1\SyncController;
use Illuminate\Support\Facades\Route;

Route::prefix('v1')->group(function (): void {
    Route::post('auth/login', [AuthController::class, 'login'])->middleware('throttle:login');
    Route::post('auth/renew', [AuthController::class, 'renew'])->middleware('throttle:renew');
    Route::post('auth/owner-signup', [OwnerAccountController::class, 'signup'])->middleware('throttle:signup');
    Route::post('auth/family-invite/inspect', [OwnerAccountController::class, 'inspectFamilyInvite'])->middleware('throttle:signup');
    Route::post('auth/family-signup', [OwnerAccountController::class, 'familySignup'])->middleware('throttle:signup');

    Route::middleware('auth.opaque')->group(function (): void {
        Route::post('auth/logout', [AuthController::class, 'logout']);
        Route::get('auth/me', [AuthController::class, 'me']);
        Route::get('auth/sessions', [AuthController::class, 'sessions'])->middleware(['tenant', 'permission:sessions.view_own']);
        Route::delete('auth/sessions/{session}', [AuthController::class, 'revokeSession'])->middleware(['tenant', 'permission:sessions.revoke_own']);
        Route::post('auth/switch-organization', [AuthController::class, 'switchOrganization']);
        Route::post('auth/switch-farm', [AuthController::class, 'switchFarm']);
        Route::get('auth/profile', [ProfileController::class, 'show']);
        Route::patch('auth/profile', [ProfileController::class, 'update']);
        Route::post('auth/profile/photo', [ProfileController::class, 'uploadPhoto']);
        Route::delete('auth/profile/photo', [ProfileController::class, 'deletePhoto']);
        Route::get('auth/profile/photo', [ProfileController::class, 'photo']);
        Route::get('organizations', [OrganizationController::class, 'index']);

        Route::middleware('tenant')->group(function (): void {
            Route::get('profile-photos/{user}', [ProfileController::class, 'memberPhoto']);
            Route::get('family-members', [FamilyAccountController::class, 'index'])->middleware('permission:users.view');
            Route::delete('family-members/{membership}', [FamilyAccountController::class, 'remove'])->middleware('permission:users.manage');
            Route::post('family-members/{membership}/restore', [FamilyAccountController::class, 'restore'])->middleware('permission:users.manage');
            Route::get('family-invite', [FamilyAccountController::class, 'invite'])->middleware('permission:users.manage');
            Route::post('family-invite', [FamilyAccountController::class, 'rotateInvite'])->middleware('permission:users.manage');
            Route::delete('family-invite', [FamilyAccountController::class, 'disableInvite'])->middleware('permission:users.manage');
            Route::get('organizations/{organization}', [OrganizationController::class, 'show'])->middleware('permission:organizations.view');
            Route::patch('organizations/{organization}', [OrganizationController::class, 'update'])->middleware('permission:organizations.update');
            Route::get('farms', [FarmController::class, 'index'])->middleware('permission:farms.view');
            Route::post('farms', [FarmController::class, 'store'])->middleware('permission:farms.create');
            Route::get('farms/{farm}', [FarmController::class, 'show'])->middleware('permission:farms.view');
            Route::patch('farms/{farm}', [FarmController::class, 'update'])->middleware('permission:farms.update');
            Route::delete('farms/{farm}', [FarmController::class, 'destroy'])->middleware('permission:farms.archive');
            Route::get('farms/{farm}/sheds', [ShedController::class, 'index'])->middleware('permission:sheds.view');
            Route::post('farms/{farm}/sheds', [ShedController::class, 'store'])->middleware('permission:sheds.create');
            Route::get('sheds/{shed}', [ShedController::class, 'show'])->middleware('permission:sheds.view');
            Route::patch('sheds/{shed}', [ShedController::class, 'update'])->middleware('permission:sheds.update');
            Route::delete('sheds/{shed}', [ShedController::class, 'destroy'])->middleware('permission:sheds.archive');
            Route::get('animal-species', [AnimalSpeciesController::class, 'index'])->middleware('permission:animals.view');
            Route::get('animal-breeds', [AnimalBreedController::class, 'index'])->middleware('permission:animal_breeds.view');
            Route::post('animal-breeds', [AnimalBreedController::class, 'store'])->middleware('permission:animal_breeds.manage');
            Route::get('animal-breeds/{breed}', [AnimalBreedController::class, 'show'])->middleware('permission:animal_breeds.view');
            Route::patch('animal-breeds/{breed}', [AnimalBreedController::class, 'update'])->middleware('permission:animal_breeds.manage');
            Route::delete('animal-breeds/{breed}', [AnimalBreedController::class, 'destroy'])->middleware('permission:animal_breeds.manage');
            Route::get('animal-groups', [AnimalGroupController::class, 'index'])->middleware('permission:animal_groups.view');
            Route::post('animal-groups', [AnimalGroupController::class, 'store'])->middleware('permission:animal_groups.manage');
            Route::get('animal-groups/{group}', [AnimalGroupController::class, 'show'])->middleware('permission:animal_groups.view');
            Route::patch('animal-groups/{group}', [AnimalGroupController::class, 'update'])->middleware('permission:animal_groups.manage');
            Route::delete('animal-groups/{group}', [AnimalGroupController::class, 'destroy'])->middleware('permission:animal_groups.manage');
            Route::get('animals', [AnimalController::class, 'index'])->middleware('permission:animals.view');
            Route::post('animals', [AnimalController::class, 'store'])->middleware('permission:animals.create');
            Route::get('animals/{animal}/movements', [AnimalMovementController::class, 'index'])->middleware('permission:animal_movements.view');
            Route::post('animals/{animal}/movements', [AnimalMovementController::class, 'store'])->middleware('permission:animals.move');
            Route::get('animals/{animal}/weights', [AnimalWeightController::class, 'index'])->middleware('permission:animals.view_weight_history');
            Route::post('animals/{animal}/weights', [AnimalWeightController::class, 'store'])->middleware('permission:animals.record_weight');
            Route::get('animals/{animal}/status-history', [AnimalStatusController::class, 'index'])->middleware('permission:animals.view_status_history');
            Route::post('animals/{animal}/status-changes', [AnimalStatusController::class, 'store'])->middleware('permission:animals.change_status');
            Route::get('animals/{animal}', [AnimalController::class, 'show'])->middleware('permission:animals.view');
            Route::patch('animals/{animal}', [AnimalController::class, 'update'])->middleware('permission:animals.update');
            Route::delete('animals/{animal}', [AnimalController::class, 'destroy'])->middleware('permission:animals.archive');
            Route::post('animals/{animal}/restore', [AnimalController::class, 'restore'])->middleware('permission:animals.restore');
            Route::get('animal-movements/{movement}', [AnimalMovementController::class, 'show'])->middleware('permission:animal_movements.view');
            Route::post('animal-movements/{movement}/approve', [AnimalMovementController::class, 'approve'])->middleware('permission:animal_movements.approve');
            Route::post('animal-movements/{movement}/reject', [AnimalMovementController::class, 'reject'])->middleware('permission:animal_movements.reject');
            Route::post('animal-movements/{movement}/cancel', [AnimalMovementController::class, 'cancel'])->middleware('permission:animal_movements.cancel');
            Route::get('animal-weights/{weight}', [AnimalWeightController::class, 'show'])->middleware('permission:animals.view_weight_history');
            Route::post('animal-weights/{weight}/correct', [AnimalWeightController::class, 'correct'])->middleware('permission:animals.correct_weight');
            Route::get('inventory', [InventoryController::class, 'dashboard'])->middleware('permission:inventory.view');
            Route::get('inventory/{kind}', [InventoryController::class, 'index'])->middleware('permission:inventory.view');
            Route::get('inventory/{kind}/exports/receipt', [InventoryController::class, 'receiptExport'])->middleware('permission:inventory.export');
            Route::get('inventory/{kind}/exports/spreadsheet', [InventoryController::class, 'spreadsheetExport'])->middleware('permission:inventory.export');
            Route::post('inventory/{kind}/items', [InventoryController::class, 'store'])->middleware('permission:inventory.manage');
            Route::patch('inventory/{kind}/items/{item}', [InventoryController::class, 'update'])->middleware('permission:inventory.manage');
            Route::delete('inventory/{kind}/items/{item}', [InventoryController::class, 'archive'])->middleware('permission:inventory.manage');
            Route::post('inventory/{kind}/items/{item}/receipts', [InventoryController::class, 'receipt'])->middleware('permission:inventory.manage');
            Route::get('inventory/{kind}/items/{item}/movements', [InventoryController::class, 'movements'])->middleware('permission:inventory.view');
            Route::get('milk/daily', [MilkProductionController::class, 'daily'])->middleware('permission:milk.view');
            Route::post('milk/entries/bulk', [MilkProductionController::class, 'storeBulk'])->middleware('permission:milk.create');
            Route::post('milk/entries/{entry}/correct', [MilkProductionController::class, 'correct'])->middleware('permission:milk.correct');
            Route::get('sync/bootstrap', [SyncController::class, 'bootstrap']);
            Route::get('sync/changes', [SyncController::class, 'changes']);
        });
    });
});
