<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

return new class extends Migration
{
    public function up(): void
    {
        $now = now();
        $newSymptoms = [
            ['chronic_cough','Persistent chronic cough','Purani musalsal khansi','respiratory',false],
            ['enlarged_nodes','Persistently enlarged lymph nodes','Musalsal barhay huay ghudood','general',false],
            ['circling','Circling, head tilt or one-sided facial weakness','Ghoomna, sar terha ya aik taraf chehra kamzor','neurologic',true],
            ['stiff_gait','Generalized stiffness or rigid gait','Poora jism akra ya sakht chaal','neurologic',true],
            ['flaccid_paralysis','Flaccid weakness or paralysis','Dheeli kamzori ya falij','neurologic',true],
            ['straining_urinate','Repeated straining to urinate','Bar bar peshab ke liye zor','urinary',true],
            ['no_urine','Little or no urine passed','Bohat kam ya bilkul peshab nahi','urinary',true],
            ['brisket_pain','Pain/grunt when moving or pressing brisket','Chalnay ya seena dabane par dard/karahna','digestive',true],
            ['muzzle_edema','Swollen muzzle, lips or tongue','Thothni, hont ya zaban ki soojan','oral',true],
            ['lip_scabs','Thick crusts or scabs on lips/muzzle','Honton ya thothni par moti papri','skin',false],
            ['eye_nose_discharge','Discharge from both eyes and nose','Aankhon aur naak dono se mada','respiratory',false],
            ['joint_pain','Painful swollen joints or reluctant movement','Dardnaak soojay jor ya chalne se gurez','musculoskeletal',false],
        ];
        foreach ($newSymptoms as [$code,$name,$roman,$system,$emergency]) {
            DB::table('health_symptoms')->insert(['id'=>(string)Str::uuid7(),'code'=>$code,'name'=>$name,'name_roman_urdu'=>$roman,'body_system'=>$system,'is_emergency'=>$emergency,'emergency_message'=>$emergency?'Urgent veterinary assessment is required.':null,'is_active'=>true,'created_at'=>$now,'updated_at'=>$now]);
        }

        $merck = 'Merck Veterinary Manual';
        $woah = 'World Organisation for Animal Health (WOAH)';
        $commonNo = 'Do not use human medicine, an unverified antibiotic or injection, or an unlabeled dose. Observe milk and meat withdrawal.';
        $commonNoRu = 'Insano ki dawa, ghair tasdeeq antibiotic/injection ya baghair label dose na dein. Doodh aur gosht withdrawal ka khayal rakhein.';
        $rows = [
            ['bovine_tb','Bovine tuberculosis','Gai bhains ki TB',['cattle','buffalo','goat'],'A chronic zoonotic infection that may cause progressive weight loss, persistent cough and enlarged lymph nodes.','Purani zoonotic infection jo wazan kam, musalsal khansi aur barhay ghudood kar sakti hai.','Isolate, avoid raw milk and close aerosol exposure, and notify veterinary authorities.','Alag karein, kacha doodh aur qareebi saans ka rabta band karein aur authority ko batayein.','Official testing and control are required; routine farm treatment is not appropriate.','Official test aur control zaroori; farm par aam ilaaj munasib nahi.','emergency',$woah,'https://www.woah.org/en/disease/bovine-tuberculosis/',['chronic_cough'=>5,'weight_loss'=>3,'enlarged_nodes'=>4,'reduced_milk'=>1]],
            ['leptospirosis','Leptospirosis','Leptospirosis / peshab se phailne wali bimari',['cattle','buffalo','goat'],'A zoonotic bacterial disease associated with fever, abortion, reduced milk, jaundice and sometimes red urine.','Zoonotic bacterial bimari jo bukhar, hamal zaya, doodh kam, peela pan aur laal peshab kar sakti hai.','Use gloves, isolate from shared water, avoid urine contact and restrict raw milk.','Dastanay, alag pani, peshab se bachao aur kacha doodh band karein.','A veterinarian selects an effective antimicrobial early and supportive care; herd vaccination and rodent/water control prevent recurrence.','Vet jaldi munasib antimicrobial aur supportive care select kare; vaccine aur choohay/pani control bachao hain.','same_day',$merck,'https://www.merckvetmanual.com/infectious-diseases/leptospirosis/leptospirosis-in-ruminants',['fever'=>2,'abortion'=>4,'jaundice'=>3,'red_urine'=>4,'reduced_milk'=>2]],
            ['salmonellosis','Salmonellosis','Salmonella infection',['cattle','buffalo','goat'],'A zoonotic enteric infection causing fever, severe diarrhea, dehydration and sometimes abortion or septicemia.','Zoonotic aant ki infection jo bukhar, shadeed dast, pani ki kami aur kabhi abortion/septicemia karti hai.','Isolate, use gloves, separate manure, milk and equipment, and provide water only if swallowing.','Alag, dastanay, gobar/doodh/samaan juda aur nigal sakay to pani dein.','Culture and susceptibility guide antimicrobial use in systemic disease; fluids and electrolyte correction are central.','Culture/sensitivity systemic case mein antimicrobial guide karti hai; fluids/electrolytes bunyadi ilaaj hain.','emergency',$merck,'https://www.merckvetmanual.com/digestive-system/salmonellosis/salmonellosis-in-animals',['fever'=>3,'profuse_diarrhea'=>5,'dehydration'=>4,'abortion'=>2,'weakness'=>2]],
            ['listeriosis','Listeriosis','Listeriosis / silage wali ghoomnay ki bimari',['cattle','buffalo','goat'],'A zoonotic infection that can cause circling, head tilt, facial weakness, fever, abortion or septicemia.','Zoonotic infection jo ghoomna, sar terha, chehra kamzor, bukhar, abortion ya septicemia kar sakti hai.','Stop suspect spoiled silage, isolate, keep safe from obstacles and seek emergency care for neurologic signs.','Mashkook kharab silage band, alag, rukawaton se mehfooz aur asabi alamat mein emergency madad lein.','Early veterinarian-selected antimicrobial therapy plus fluids and nursing offers the best chance; late neurologic disease responds poorly.','Jaldi vet-selected antimicrobial, fluids aur nursing behtar chance dete hain; der se response kam hota hai.','emergency',$merck,'https://www.merckvetmanual.com/infectious-diseases/listeriosis/listeriosis-in-animals',['circling'=>5,'neurologic_signs'=>4,'fever'=>2,'abortion'=>3,'excess_saliva'=>2]],
            ['ibr','Infectious bovine rhinotracheitis (IBR)','IBR / gai ki viral naak saans bimari',['cattle','buffalo'],'A contagious herpesvirus disease causing fever, red inflamed nose, eye/nose discharge, cough, reduced milk and sometimes abortion.','Mutaddi herpes virus jo bukhar, surkh naak, aankh/naak mada, khansi, doodh kam aur abortion kar sakta hai.','Isolate, stop movement, improve ventilation without chilling and separate equipment.','Alag, movement band, thand ke baghair hawa behtar aur samaan juda karein.','Treatment is supportive; a veterinarian treats secondary bacterial complications. Biosecurity and an appropriate vaccination program control disease.','Ilaaj supportive; vet secondary bacterial complication treat karta hai. Biosecurity aur vaccine control hain.','same_day',$merck,'https://www.merckvetmanual.com/respiratory-system/infectious-bovine-rhinotracheitis/infectious-bovine-rhinotracheitis',['fever'=>2,'eye_nose_discharge'=>5,'cough'=>3,'reduced_milk'=>2,'abortion'=>2]],
            ['bvd','Bovine viral diarrhea','BVD / gai ki viral dast bimari',['cattle','buffalo'],'BVD can cause fever, diarrhea, mouth erosions, production loss, reproductive failure and persistently infected calves.','BVD bukhar, dast, munh chalay, paidawar kam, reproduction loss aur PI bachay karta hai.','Isolate, prevent contact with pregnant cattle, use separate equipment and maintain hydration if safe.','Alag, pregnant gai se door, samaan juda aur mehfooz ho to pani dein.','Treatment is supportive. Antigen/PCR testing identifies persistently infected animals; control uses removal, biosecurity and vaccination.','Ilaaj supportive. Antigen/PCR se PI janwar milte hain; removal, biosecurity aur vaccine control hain.','same_day',$merck,'https://www.merckvetmanual.com/infectious-diseases/bovine-viral-diarrhea/bovine-viral-diarrhea-and-mucosal-disease-complex',['fever'=>2,'diarrhea'=>3,'oral_erosions'=>4,'abortion'=>2,'reduced_milk'=>2]],
            ['q_fever','Q fever (Coxiellosis)','Q fever / abortion wali zoonotic infection',['cattle','buffalo','goat'],'A major zoonosis often associated with abortion, weak offspring and heavy contamination of birth materials.','Aham zoonotic bimari jo abortion, kamzor bachay aur birth material ki shadeed aloodgi se judi hai.','Isolate birthing area, use gloves/mask, securely contain placenta, restrict raw milk and disinfect appropriately.','Bacha dene ki jagah alag, gloves/mask, jer mehfooz band, kacha doodh band aur safai karein.','PCR/serology and herd investigation confirm risk; treatment and control decisions are veterinarian/public-health led.','PCR/serology aur herd investigation; ilaaj/control vet aur public health lead karein.','emergency',$woah,'https://www.woah.org/en/disease/q-fever/',['abortion'=>5,'weak_newborn'=>3,'retained_placenta'=>2,'fever'=>1]],
            ['contagious_agalactia','Contagious agalactia','Bakri ka mutaddi doodh band syndrome',['goat'],'A mycoplasma syndrome causing mastitis, sudden milk loss, conjunctivitis and arthritis; carriers may persist.','Mycoplasma syndrome jo mastitis, achanak doodh band, aankh infection aur jor soojan karta hai; carrier reh sakte hain.','Isolate, stop milk sharing, separate milking equipment and do not feed affected raw milk to young animals.','Alag, doodh sharing band, milking samaan juda aur mutasir kacha doodh bachon ko na dein.','PCR/culture is important. Susceptibility-aware antimicrobials may improve signs but do not reliably clear carriers.','PCR/culture zaroori. Sensitivity ke mutabiq antimicrobials alamat behtar magar carrier khatam nahi karte.','same_day',$merck,'https://www.merckvetmanual.com/reproductive-system/contagious-agalactia/contagious-agalactia-in-small-ruminants',['udder_swelling'=>3,'abnormal_milk'=>4,'reduced_milk'=>5,'cloudy_eye'=>2,'joint_pain'=>4]],
            ['sheep_goat_pox','Sheep and goat pox','Bakri/bher pox',['goat'],'A contagious viral disease causing fever and widespread firm skin papules, nodules or scabs, sometimes pneumonia.','Mutaddi viral bimari jo bukhar aur phailay sakht jildi danay/gaanth/papri aur kabhi pneumonia karti hai.','Isolate, stop movement, control insects and shared equipment, and notify veterinary authorities.','Alag, movement band, keeray aur mushtarka samaan control aur authority ko batayein.','No specific antiviral treatment; supportive care and secondary-infection management are veterinarian directed. Vaccination controls outbreaks.','Khas antiviral nahi; supportive aur secondary infection ilaaj vet kare. Vaccine outbreak control karta hai.','emergency',$woah,'https://www.woah.org/en/disease/sheep-pox-and-goat-pox/',['fever'=>3,'skin_nodules'=>5,'crusty_skin'=>3,'swollen_lymph_nodes'=>2,'nasal_discharge'=>1]],
            ['bluetongue','Bluetongue','Bluetongue / keere se phailne wali viral bimari',['cattle','buffalo','goat'],'A midge-borne viral disease that may cause fever, swollen muzzle/tongue, mouth lesions, salivation and lameness.','Midge se viral bimari jo bukhar, thothni/zaban soojan, munh chalay, ral aur langrahat karti hai.','Rest in shade, provide soft feed/water if swallowing, reduce biting insects and avoid stressful movement.','Saye mein aram, nigal sakay to narm chara/pani, kaatne walay keeray kam aur stress movement band.','There is no specific antiviral treatment; supportive care and treatment of complications are used. Prevention uses vector control and suitable vaccines.','Khas antiviral nahi; supportive aur complications ka ilaaj. Bachao vector control aur munasib vaccine.','emergency',$merck,'https://www.merckvetmanual.com/generalized-conditions/bluetongue/bluetongue-in-ruminants',['fever'=>2,'muzzle_edema'=>5,'oral_erosions'=>3,'excess_saliva'=>2,'lameness'=>3]],
            ['tetanus','Tetanus','Tetanus / jism akarnay ki bimari',['cattle','buffalo','goat'],'Clostridial neurotoxin disease causing progressive stiffness, lockjaw, erect ears, spasms and breathing failure.','Clostridial zehar jo barhti akrahat, jabra band, kaan kharay, spasms aur saans fail karta hai.','Move to a quiet dark area, minimize sound/touch, do not force feed and obtain emergency help.','Pur-sukoon andheri jagah, awaz/chhoona kam, zabardasti chara nahi aur emergency madad.','Treatment may include antitoxin, wound management, veterinarian-selected antimicrobial, sedation and intensive nursing; vaccination prevents disease.','Ilaaj antitoxin, zakhm safai, vet antimicrobial, sedation aur nursing; vaccine bachao.','emergency',$merck,'https://www.merckvetmanual.com/infectious-diseases/clostridial-diseases/tetanus-in-animals',['stiff_gait'=>5,'muscle_tremors'=>3,'swallowing_difficulty'=>3,'breathing_difficulty'=>3]],
            ['botulism','Botulism','Botulism / dheeli falij',['cattle','buffalo','goat'],'Botulinum toxin causes progressive flaccid weakness, tongue weakness, swallowing difficulty, recumbency and respiratory failure.','Botulinum zehar barhti dheeli kamzori, zaban kamzor, nigalna mushkil, girna aur saans fail karta hai.','Remove suspect feed/carcass access, keep chest upright, do not drench and obtain emergency care.','Mashkook chara/lash access band, seene ke bal rakhein, drench nahi aur emergency care.','Early antitoxin may help before toxin binds; intensive nursing, fluids and respiratory support are veterinarian managed.','Jaldi antitoxin madad kar sakta; nursing, fluids aur respiratory support vet manage kare.','emergency',$merck,'https://www.merckvetmanual.com/toxicology/botulism/botulism-in-animals',['flaccid_paralysis'=>5,'swallowing_difficulty'=>4,'weakness'=>3,'sudden_collapse'=>2]],
            ['orf','Contagious ecthyma (orf)','Orf / honton ki mutaddi papri',['goat'],'A zoonotic parapoxvirus disease causing thick painful scabs around lips and muzzle, especially in young goats.','Zoonotic parapox virus jo khas bachon mein honton/thothni par moti dardnaak papri karta hai.','Wear gloves, isolate, soften feed, disinfect equipment and protect lesions from flies without cutting scabs.','Gloves, alag, narm chara, samaan disinfect aur papri kaatay baghair makhiyon se bachao.','No specific antiviral treatment; secondary infection and flystrike are treated as needed. Live vaccine use requires outbreak-aware veterinary planning.','Khas antiviral nahi; secondary infection/flystrike zarurat par. Live vaccine vet outbreak plan se.','same_day',$merck,'https://www.merckvetmanual.com/integumentary-system/pox-diseases/contagious-ecthyma-in-sheep-and-goats',['lip_scabs'=>5,'reduced_appetite'=>2,'oral_erosions'=>2,'fever'=>1]],
            ['urolithiasis','Obstructive urolithiasis','Peshab ki pathri / rasta band',['cattle','buffalo','goat'],'Urinary stones, especially in males, can cause repeated straining, drops or no urine, belly pain and bladder rupture.','Khas nar janwar mein pathri bar bar zor, qatray/na peshab, pait dard aur bladder phatna kar sakti hai.','Remove concentrate, provide water only if comfortable, do not press the bladder or pass objects, and seek emergency care.','Dana hata, aram ho to pani, bladder na dabayein ya cheez na dalain aur emergency care.','Restoring urine flow, analgesia, fluids and often catheter/surgery are veterinarian procedures; diet and water correction prevent recurrence.','Peshab rasta, pain relief, fluids aur aksar catheter/surgery vet kare; diet/pani correction bachao.','emergency',$merck,'https://www.merckvetmanual.com/urinary-system/noninfectious-diseases-of-the-urinary-system-in-large-animals/urolithiasis-in-ruminants',['straining_urinate'=>5,'no_urine'=>5,'abdominal_pain'=>3,'reduced_appetite'=>2]],
            ['hardware_disease','Traumatic reticuloperitonitis (hardware disease)','Hardware disease / pait mein keel taar',['cattle','buffalo'],'Swallowed sharp metal can penetrate the reticulum, causing sudden appetite/milk loss, fever, arched stance and pain/grunting.','Nigal hua keel/taar reticulum chhed kar achanak bhook/doodh kam, bukhar, kamar terhi aur dard karta hai.','Restrict movement, keep on level bedding, remove access to scrap metal and arrange urgent examination.','Movement kam, seedha bistar, scrap metal access band aur urgent muaina.','Diagnosis uses pain tests and imaging. A veterinarian may use a rumen magnet, antimicrobial/supportive treatment or surgery depending on severity.','Pain tests/imaging; vet shiddat par rumen magnet, antimicrobial/supportive ya surgery use kare.','same_day',$merck,'https://www.merckvetmanual.com/digestive-system/diseases-of-the-ruminant-forestomach/traumatic-reticuloperitonitis-in-cattle',['brisket_pain'=>5,'reduced_appetite'=>3,'reduced_milk'=>2,'fever'=>2,'left_bloat'=>1]],
            ['bovine_ephemeral_fever','Bovine ephemeral fever (three-day sickness)','Teen din ka bukhar',['cattle','buffalo'],'An insect-borne viral disease causing sudden fever, stiffness, lameness, muscle tremors and recumbency, often with rapid recovery.','Keeray se viral bimari jo achanak bukhar, akrahat, langrahat, larzish aur girna karti, aksar jaldi behtar.','Complete rest, shade, water if swallowing, deep bedding and no forced walking.','Mukammal aram, saya, nigal sakay to pani, narm bistar aur zabardasti chalana nahi.','Veterinary care uses label-appropriate anti-inflammatory and supportive treatment; recumbent animals need nursing and metabolic assessment.','Vet label ke mutabiq anti-inflammatory/supportive ilaaj; giray janwar ko nursing/metabolic check.','same_day',$merck,'https://www.merckvetmanual.com/generalized-conditions/bovine-ephemeral-fever/bovine-ephemeral-fever',['fever'=>3,'stiff_gait'=>4,'lameness'=>2,'muscle_tremors'=>2,'sudden_collapse'=>3]],
        ];

        foreach ($rows as [$code,$name,$roman,$species,$summary,$summaryRu,$care,$careRu,$treat,$treatRu,$urgency,$source,$url,$links]) {
            $id=(string)Str::uuid7();
            DB::table('health_diseases')->insert(['id'=>$id,'code'=>$code,'name'=>$name,'name_roman_urdu'=>$roman,'species'=>json_encode($species),'summary'=>$summary,'summary_roman_urdu'=>$summaryRu,'immediate_care'=>$care,'immediate_care_roman_urdu'=>$careRu,'confirmation_guidance'=>$treat,'confirmation_guidance_roman_urdu'=>$treatRu,'safe_home_care'=>$care,'safe_home_care_roman_urdu'=>$careRu,'do_not_do'=>$commonNo,'do_not_do_roman_urdu'=>$commonNoRu,'feed_water_guidance'=>'Keep clean water available only when swallowing is safe; follow the disease-specific feeding precaution.','feed_water_guidance_roman_urdu'=>'Sirf mehfooz nigal sakne par saaf pani aur bimari ki khas feed ehtiyat.','urgency'=>$urgency,'source_title'=>$source,'source_url'=>$url,'source_reviewed_on'=>'2026-08-18','review_status'=>'approved','reviewed_at'=>$now,'knowledge_version'=>1,'is_active'=>true,'created_at'=>$now,'updated_at'=>$now]);
            DB::table('health_knowledge_sources')->insert(['id'=>(string)Str::uuid7(),'disease_id'=>$id,'title'=>$source,'url'=>$url,'url_hash'=>hash('sha256',$url),'publisher'=>$source,'source_type'=>'authoritative_veterinary_reference','accessed_on'=>'2026-08-18','evidence_scope'=>'Disease identity, signs, first aid, treatment approach, prevention and confirmation.','is_primary'=>true,'created_at'=>$now,'updated_at'=>$now]);
            foreach($links as $symptom=>$weight){DB::table('health_disease_symptom')->insert(['disease_id'=>$id,'symptom_id'=>DB::table('health_symptoms')->where('code',$symptom)->value('id'),'weight'=>$weight,'is_key'=>$weight>=4]);}
        }
        DB::table('health_ai_evaluation_cases')->where('case_code','EVAL-SPECIES-01')->update(['expected_disease_codes'=>json_encode(['sheep_goat_pox']),'expected_emergency'=>true,'expects_match'=>true,'review_notes'=>'Updated because goat pox is now present in the expanded approved knowledge base.','updated_at'=>$now]);
    }

    public function down(): void
    {
        DB::table('health_ai_evaluation_cases')->where('case_code','EVAL-SPECIES-01')->update(['expected_disease_codes'=>json_encode([]),'expected_emergency'=>false,'expects_match'=>false,'review_notes'=>'Species-boundary negative case.','updated_at'=>now()]);
        DB::table('health_diseases')->whereIn('code',['bovine_tb','leptospirosis','salmonellosis','listeriosis','ibr','bvd','q_fever','contagious_agalactia','sheep_goat_pox','bluetongue','tetanus','botulism','orf','urolithiasis','hardware_disease','bovine_ephemeral_fever'])->delete();
        DB::table('health_symptoms')->whereIn('code',['chronic_cough','enlarged_nodes','circling','stiff_gait','flaccid_paralysis','straining_urinate','no_urine','brisket_pain','muzzle_edema','lip_scabs','eye_nose_discharge','joint_pain'])->delete();
    }
};
